redBorder/rb-aioutliers

- .github/workflows/lint.yml
- resources/src/IA/outliers.py
- resources/src/Logger/logger.py
- resources/src/server/rest.py
Add pylint job for code quality test
> Linter action

- .github/workflows/security.yml
- .github/workflows/tests.yml
Separate security checks from unit tests workflow
> Security workflow

- .github/workflows/lint.yml
- .github/workflows/pr.yml
- .github/workflows/security.yml
- .github/workflows/tests.yml
* Updated .github/workflows/ to add a new pipeline that checks the PR format
> PR-20: Update CI workflow

- .github/workflows/security.yml
- .github/workflows/tests.yml
- resources/systemd/rb-aioutliers-rq.service
- resources/systemd/rb-aioutliers-train.service
- resources/systemd/rb-aioutliers.service
* I had updated systemd services information to use correct Working Directory, also, i made rq service to execute under scl
> PR-30: update services for rq workers to work

- resources/src/ai/outliers.py
- resources/src/ai/trainer.py
* Fixed an issue where the model failed to load correctly the loss function during training, making said training useless.
> PR-31: Fix model loss

- .github/workflows/tests.yml
- README.md
* I fixed codecov coverage report upload
> PR-32: Fix codecov

- LICENSE
- README.md
- resources/src/__main__.py
- resources/src/ai/outliers.py
- resources/src/ai/trainer.py
- resources/src/config/configmanager.py
- resources/src/druid/client.py
- resources/src/druid/query_builder.py
- resources/src/logger/logger.py
- resources/src/rbntp/ntplib.py
- resources/src/redborder/async_jobs/train_job.py
- resources/src/redborder/rq.py
- resources/src/redborder/s3.py
- resources/src/server/production.py
- resources/src/server/rest.py
- resources/tests/test_configmanager.py
- resources/tests/test_druid.py
- resources/tests/test_logger.py
- resources/tests/test_ntp.py
- resources/tests/test_outliers.py
- resources/tests/test_query_builder.py
- resources/tests/test_rq.py
- resources/tests/test_s3.py
- resources/tests/test_train_job.py
- resources/tests/test_trainer.py
* I changed the LICENSE from AGPLv3 to GPL2 because we have dependencies that are licensed under GPL2
> PR-33: Fix software LICENSE

- resources/src/ai/outliers.py
- resources/src/ai/shallow_outliers.py
- resources/tests/test_shallow_outliers.py
* Added default outlier detection model for when no model has been trained
* Added test for new model
* Fixed minor mistakes in comments and shortened some lines in outliers.py
> PR-38: Add default outliers

- .github/workflows/changelog.yml
- .github/workflows/release.yml
> PR-43: Add release workflow

- .github/workflows/changelog.yml
> PR-45: Update changelog workflow

- .github/workflows/changelog.yml
> PR-46 - Update changelog

- Doxyfile
* This PR reconfigures doxyfile
> pr-49: Reconfigure doxyfile

- .github/workflows/doxygen.yml
> PR-50: Fix work path

- Doxyfile
- resources/src/RBAIOUTLIERS.md
* Update doxyfile and create doxygen main page
> PR-52: Update doxyfile and create mainpage

- .github/workflows/doxygen.yml
> PR-52: Update doxyfile

- .github/workflows/doxygen.yml
> PR-55: Update path

- resources/src/requirements.txt
* Removed duplicated dependencies from requirements.txt
> PR-57: Resolve dependency issues

- resources/src/server/rest.py
- resources/tests/test_rest.py
* Solved the issue.
* Unified error handling in the api rest to avoid  creating a similar issue again.
> PR-57: Fix code scanning alert - Information exposure through an exception

- resources/src/ai/outliers_identifier.py
- resources/src/server/rest.py
- resources/tests/test_ip_identifier.py
* the objetive is to create a relation with outliers and the ips to identify the ips  that caused the outliers
> PR-63: Outliers identifier

- resources/src/config.ini
- Update default druid_broker port to 8082
> PR-78: Update druid broker port

- resources/src/ai/monitor.ini
- resources/src/ai/shallow_outliers.py
* [Associated Redmine task](https://redmine.redborder.lan/issues/22167).
* Extract `monitors` field from the druid query passed as parameter.
> PR-79: Adapt rb-aioutliers to work with rb_monitor
